# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Chang Liu
email: changliu0828@gmail.com
description: Software engineer in Tokyo. Notes on code, life, and ideas.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://changliu.me"
github_username:  changliu0828

# Build settings
remote_theme: b2a3e8/jekyll-theme-console
style: light
header_pages:
  - index.md
  - about.md
header_pages_zh:
  - zh/index.md
  - zh/about.md
footer: '&copy;2020–2026 Chang Liu. <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>'
footer_zh: '&copy;2020–2026 Chang Liu. <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>'

permalink: /:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
    values:
      lang: en
  - scope:
      path: "zh"
    values:
      lang: zh
  - scope:
      path: "_posts/zh"
    values:
      lang: zh
      permalink: /zh/:year/:month/:day/:title.html


tracking:
  script_src:
    - https://www.googletagmanager.com/gtag/js?id=G-3VR9KTM0WS
    - /assets/scripts/ga.js

plugins:
  - jekyll-admin

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
