baseURL = "https://changliu0828.github.io/"
languageCode = "en-us"
title = "刘畅"
theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
[params.author]
  name = "刘畅"
  email = "changliu0828@gmail.com"

# Header Menu
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4
