baseurl = "http://changliu0828.github.io"
DefaultContentLanguage = "ch"
languageCode = "en"

theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[languages]
  [languages.ch]
    languageName = "ZH"
    title = "刘畅的博客"
    contentDir = "content/ch"
    weight = 1
    [[languages.ch.menu.main]]
      name = "主页"
      url = "/"
      weight = 1
    [[languages.ch.menu.main]]
      name = "分类"
      url = "/categories/"
      weight = 2
    [[languages.ch.menu.main]]
      name = "标签"
      url = "/tags/"
      weight = 3
    [[languages.ch.menu.main]]
      name = "仪表盘"
      url = "/dashboard/"
      weight = 4
  [languages.en]
    languageName = "EN"
    title = "Chang Liu's Blog"
    contentDir = "content/en"
    weight = 2
    [[languages.en.menu.main]]
      name = "Home"
      url = "/en/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Categories"
      url = "/en/categories/"
      weight = 2
    [[languages.en.menu.main]]
      name = "Tags"
      url = "/en/tags/"
      weight = 3   

[permalinks]
    post = "/post/:filename/"

[params]
    description = "Chang Liu's Blog"
    footer = "&copy; [Chang Liu](www.changliu.me) 2021 | [Contact](mailto:changliu0828@gmail.com)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    style = "autumn"
    lineNos = true
    guessSyntax = true
    
[params.valine]
  enable = true
  appId = 'zNMMLLQ0MYK2AKAgq6nC93gV-gzGzoHsz'
  appKey = 'KfJ8vAFRca4uVeQWMNljT07B'
  notify = false # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  visitor = true
  placeholder = '...'
  lang = 'en'

