baseURL = "https://changliu0828.github.io/"
languageCode = "en-us"
title = "刘畅"
theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
summaryLength=20
[params]
[params.author]
  name = "刘畅"
  email = "changliu0828@gmail.com"

# Header Menu
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 1
[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
