baseURL = "https://changliu0828.github.io/"
languageCode = "en-us"
theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
summaryLength=20
copyright = "&copy; Copyright 2020 Chang Liu"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Chang Liu's Blog"

[params]
[params.author]
  name = "Chang"
  email = "changliu0828@gmail.com"

# Header Menu
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 2

[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 2
