baseURL = "https://changliu0828.github.io/"
hasCJKLanguage = true
languageCode = "en"
defaultContentLanguage = "en"
showToc = true

theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
summaryLength=20
copyright = "&copy; Copyright 2020 Chang Liu"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "刘畅的博客"

[params]
  dateFormat = "2006-01-02"
[params.author]
  name = "Chang"
  email = "changliu0828@gmail.com"
[markup]
  [markup.highlight]
    codeFences = true 
    hl_Lines = ""
    style = "friendly"
    lineNos = true
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
[taxonomies]
  tag = "tags"
[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 2 
