baseURL = "https://changliu0828.github.io/"
hasCJKLanguage = true
languageCode = "en"
defaultContentLanguage = "en"
showToc = true

theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
summaryLength=20
copyright = "&copy; Copyright 2020 Chang Liu"

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "刘畅的博客"

[params]
  dateFormat = "2006-01-02"
[params.author]
  name = "Chang"
  email = "changliu0828@gmail.com"
[markup]
  [markup.highlight]
    codeFences          = true 
    pygmentsUseClassic  = true
    pygmentsCodeFences  = true
    style               = "autumn"
    noClasses           = false
    hl_Lines = ""
    lineNos = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
# Header Menu
[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4
