baseurl = "http://changliu0828.github.io"
languageCode = "en"
title = "Chang Liu's Blog"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[params]
    description = "Chang Liu's Blog"
    footer = "&copy; [Chang Liu](www.changliu.me) 2020 | [Contact](mailto:changliu0828@gmail.com)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "autumn" 
  [markup.tableOfContents]
    startLevel = 1
    
[params.valine]
  enable = true
  appId = 'zNMMLLQ0MYK2AKAgq6nC93gV-gzGzoHsz'
  appKey = 'KfJ8vAFRca4uVeQWMNljT07B'
  notify = false # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  visitor = true
  placeholder = '...'
  lang = 'en'
