baseURL = "https://changliu0828.github.io/"
languageCode = "en-us"
title = "刘畅的博客"
theme = ["whiteplain-light", "whiteplain"]
disqusShortname = "ChangLiu"
summaryLength=20
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2020 Chang Liu"
[params]
[params.author]
  name = "刘畅"
  email = "changliu0828@gmail.com"

# Header Menu
[[menu.main]]
  name = "归档"
  identifier = "archives"
  url = "/archives/"
  weight = 1
[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true 
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 2
